{% set name = "chainer" %}
{% set version = "7.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 179f06176f8d7a42385bc7811956db04e68213cfe30f5081491b9e2b6ff70de8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.5
    - setuptools
    - typing_extensions
    - filelock
    - numpy >=1.9.0
    - protobuf >=3.0.0
    - six >=1.9.0

test:
  commands:
    - pip check
  requires:
    - pip
  imports:
    - chainer
    - chainer.backends
    - chainer.dataset
    - chainer.dataset.tabular
    - chainer.datasets
    - chainer.distributions
    - chainer.exporters
    - chainer.functions
    - chainer.functions.activation
    - chainer.functions.array
    - chainer.functions.connection
    - chainer.functions.evaluation
    - chainer.functions.loss
    - chainer.functions.math
    - chainer.functions.noise
    - chainer.functions.normalization
    - chainer.functions.pooling
    - chainer.functions.rnn
    - chainer.functions.theano
    - chainer.functions.util
    - chainer.function_hooks
    - chainer.iterators
    - chainer.initializers
    - chainer.links
    - chainer.links.activation
    - chainer.links.caffe
    - chainer.links.caffe.protobuf3
    - chainer.links.connection
    - chainer.links.loss
    - chainer.links.model
    - chainer.links.model.vision
    - chainer.links.normalization
    - chainer.links.rnn
    - chainer.links.theano
    - chainer.link_hooks
    - chainer.graph_optimizations
    - chainer.optimizers
    - chainer.optimizer_hooks
    - chainer.serializers
    - chainer.testing
    - chainer.training
    - chainer.training.extensions
    - chainer.training.triggers
    - chainer.training.updaters
    - chainer.utils
    - chainermn
    - chainermn.communicators
    - chainermn.datasets
    - chainermn.extensions
    - chainermn.functions
    - chainermn.iterators
    - chainermn.links
    - chainermn.testing

about:
  home: https://chainer.org/
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: A flexible framework of neural networks
  description: |
    Chainer is a Python-based deep learning framework aiming at flexibility.
    It provides automatic differentiation APIs based on the define-by-run
    approach (a.k.a. dynamic computational graphs) as well as object-oriented
    high-level APIs to build and train neural networks. It also supports
    CUDA/cuDNN using CuPy for high performance training and inference.
  doc_url: https://docs.chainer.org/en/stable
  dev_url: https://github.com/chainer/chainer

extra:
  recipe-maintainers:
    - nehaljwani
